### ISSUE TITLE
I get a different date in model

### ISSUE THREAD

**Issue by brujo696** [adamalbrecht/ngQuickDate#92]
the widget save a next day in the model
i need help :(

![image](http://i.imgur.com/k5JPLju.png)

"sorry my english, is very bad"

**Comment by phoopee3** [comment]
you need to make sure you are converting the date appropriately when pulling the info from the database. for me, I had to convert it to a JS date object. So in the DB if I had the date (in format YYYY-MM-DD) of '2014-09-02' then I had to create a new date object like:

```
var tempDate = new Date(2014, 8, 2);
```

You have to do the month - 1 because the months in JS are zero based.
